'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
type View='dashboard'|'leads'|'copilot'|'recommendations';
type Lead={id:string;score:number;value:number;temperature:string;customers?:{name:string;email?:string}|null};
type Sale={amount:number;sale_date:string}; type Expense={amount:number;expense_date:string};
export default function Home(){const[session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);if(loading)return <div className="login"><div className="muted">Loading BizPilot…</div></div>;if(!session)return <div className="login"><form className="login-card" onSubmit={async e=>{e.preventDefault();setError('');const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setError(r.error.message);else if(mode==='signup'&&!r.data.session)setError('Check your email to confirm your account.')}}><div className="brand">BizPilot<span> AI</span></div><h2>{mode==='login'?'Welcome back':'Create your account'}</h2><p className="muted">Your AI business copilot.</p>{error&&<div className="error">{error}</div>}<label className="muted">Email</label><input className="input" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><label className="muted">Password</label><input className="input" type="password" required minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn" style={{width:'100%'}}>{mode==='login'?'Log in':'Sign up'}</button><button type="button" className="btn secondary" style={{width:'100%',marginTop:10}} onClick={()=>{setMode(mode==='login'?'signup':'login');setError('')}}>{mode==='login'?'Create an account':'I already have an account'}</button></form></div>;return <App session={session}/>}
async function api(path:string,session:any,options?:RequestInit){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`,...(options?.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
function useData(session:any){const[data,setData]=useState<any>({leads:[],sales:[],expenses:[]});const[error,setError]=useState('');useEffect(()=>{Promise.all([api('/api/leads',session),api('/api/sales',session),api('/api/expenses',session)]).then(([l,s,e])=>setData({leads:l.leads||[],sales:s.sales||[],expenses:e.expenses||[]})).catch(e=>setError(e.message))},[session]);return{...data,error}}
function App({session}:{session:any}){const[view,setView]=useState<View>('dashboard');return <div className="app"><aside className="sidebar"><div className="brand">BizPilot<span> AI</span></div><nav className="nav">{(['dashboard','leads','copilot','recommendations'] as View[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</nav><button className="nav" style={{position:'absolute',bottom:20,border:0,background:'transparent'}} onClick={()=>supabase.auth.signOut()}>Log out</button></aside><main className="main"><div className="top"><div><div className="title">{view==='dashboard'?'Business overview':view==='leads'?'Lead intelligence':view==='copilot'?'AI Copilot':'Recommendations'}</div><div className="muted" style={{fontSize:13,marginTop:5}}>{session.user.email}</div></div></div>{view==='dashboard'?<Overview session={session}/>:view==='leads'?<Leads session={session}/>:view==='copilot'?<Copilot session={session}/>:<Recommendations session={session}/>}</main></div>}
function Overview({session}:{session:any}){const{leads,sales,expenses,error}=useData(session);const revenue=sales.reduce((a:number,x:Sale)=>a+Number(x.amount||0),0),cost=expenses.reduce((a:number,x:Expense)=>a+Number(x.amount||0),0),pipeline=leads.reduce((a:number,x:Lead)=>a+Number(x.value||0),0);return <><div className="grid4"><Metric label="Revenue" value={`$${revenue.toLocaleString()}`}/><Metric label="Expenses" value={`$${cost.toLocaleString()}`}/><Metric label="Active Leads" value={String(leads.filter((x:Lead)=>x.temperature!=='cold').length)}/><Metric label="Pipeline" value={`$${pipeline.toLocaleString()}`}/></div>{error?<div className="card" style={{marginTop:14}}><div className="error">{error}</div><div className="muted">Configure Supabase and run schema.sql.</div></div>:<div className="grid2"><div className="card"><h3>Priority leads</h3>{leads.slice(0,8).map((l:Lead)=><div className="row" key={l.id}><div><span className="score">{l.score}</span> <strong>{l.customers?.name||'Lead'}</strong></div><span className={`pill ${l.temperature}`}>{l.temperature}</span></div>)}{!leads.length&&<div className="muted">No leads yet.</div>}</div><div className="card"><h3>BizPilot AI</h3><p className="muted">Your sales, expenses, customers and leads become practical business actions.</p></div></div>}</>}
function Metric({label,value}:{label:string;value:string}){return <div className="card"><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div>}
function Leads({session}:{session:any}){const{leads,error}=useData(session);return <div className="card"><h3>Leads ranked by score</h3>{error&&<div className="error">{error}</div>}{leads.map((l:Lead)=><div className="row" key={l.id}><div><span className="score">{l.score}</span> <strong>{l.customers?.name||'Lead'}</strong></div><div><span className={`pill ${l.temperature}`}>{l.temperature}</span> <span className="muted">${Number(l.value||0).toLocaleString()}</span></div></div>)}</div>}
function Copilot({session}:{session:any}){const[q,setQ]=useState(''),[messages,setMessages]=useState<any[]>([]),[busy,setBusy]=useState(false);const ask=async(text:string)=>{if(!text.trim()||busy)return;setMessages(m=>[...m,{role:'user',text}]);setQ('');setBusy(true);try{const d=await api('/api/ai/copilot',session,{method:'POST',body:JSON.stringify({question:text})});setMessages(m=>[...m,{role:'ai',text:d.answer}])}catch(e:any){setMessages(m=>[...m,{role:'ai',text:e.message}])}finally{setBusy(false)}};return <div className="card chat"><div className="messages">{!messages.length&&<p className="muted">Ask about your actual business data.</p>}{messages.map((m,i)=><div className={`bubble ${m.role==='user'?'user':''}`} key={i}>{m.text}</div>)}{busy&&<div className="bubble loading">Thinking…</div>}</div><div className="chatbar"><input className="input" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask(q)} placeholder="Ask BizPilot…"/><button className="btn" onClick={()=>ask(q)}>Ask</button></div></div>}
function Recommendations({session}:{session:any}){const[r,setR]=useState<any>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');useEffect(()=>{api('/api/ai/copilot',session).then(setR).catch(e=>setError(e.message)).finally(()=>setBusy(false))},[session]);if(busy)return <div className="card"><p className="muted">Generating today's business brief…</p></div>;if(error)return <div className="card"><div className="error">{error}</div></div>;return <div className="card"><h3>Today's business brief</h3><p style={{whiteSpace:'pre-wrap',lineHeight:1.7}}>{r.synthesis}</p><hr style={{borderColor:'#262b36'}}/><p className="muted"><strong>Financial:</strong> {r.financial}</p><p className="muted"><strong>Sales:</strong> {r.sales}</p><p className="muted"><strong>Customers:</strong> {r.customer}</p></div>}
