'use client';

import { useEffect, useState } from 'react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);

type View = 'dashboard'|'leads'|'copilot'|'recommendations';
type Lead = {id:string; score:number; value:number; temperature:string; customers?:{name:string;email?:string}|null};
type Sale = {amount:number; sale_date:string};
type Expense = {amount:number; expense_date:string};

export default function Home(){
 const [session,setSession]=useState<any>(null); const [view,setView]=useState<View>('dashboard'); const [loading,setLoading]=useState(true); const [authMode,setAuthMode]=useState<'login'|'signup'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>subscription.unsubscribe()},[]);
 if(loading)return <div className="login"><div className="muted">Loading BizPilot…</div></div>;
 if(!session)return <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} error={error} setError={setError}/>;
 return <Dashboard session={session} view={view} setView={setView} onLogout={()=>supabase.auth.signOut()}/>;
}
function Auth(p:any){const submit=async(e:any)=>{e.preventDefault();p.setError('');const r=p.mode==='login'?await supabase.auth.signInWithPassword({email:p.email,password:p.password}):await supabase.auth.signUp({email:p.email,password:p.password});if(r.error)p.setError(r.error.message);else if(p.mode==='signup'&&!r.data.session)p.setError('Check your email to confirm your account.');};return <div className="login"><form className="login-card" onSubmit={submit}><div className="brand">BizPilot<span> AI</span></div><h2>{p.mode==='login'?'Welcome back':'Create your account'}</h2><p className="muted">Your AI business copilot.</p>{p.error&&<div className="error">{p.error}</div>}<label className="muted">Email</label><input className="input" type="email" required value={p.email} onChange={e=>p.setEmail(e.target.value)}/><label className="muted">Password</label><input className="input" type="password" required minLength={6} value={p.password} onChange={e=>p.setPassword(e.target.value)}/><button className="btn" style={{width:'100%'}}>{p.mode==='login'?'Log in':'Sign up'}</button><button type="button" className="btn secondary" style={{width:'100%',marginTop:10}} onClick={()=>{p.setMode(p.mode==='login'?'signup':'login');p.setError('')}}>{p.mode==='login'?'Create an account':'I already have an account'}</button></form></div>}
function Dashboard({session,view,setView,onLogout}:{session:any;view:View;setView:(v:View)=>void;onLogout:()=>void}){return <div className="app"><aside className="sidebar"><div className="brand">BizPilot<span> AI</span></div><nav className="nav">{(['dashboard','leads','copilot','recommendations'] as View[]).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v[0].toUpperCase()+v.slice(1)}</button>)}</nav><button className="nav" style={{position:'absolute',bottom:20,border:0,background:'transparent',color:'#9aa1b0',padding:12}} onClick={onLogout}>Log out</button></aside><main className="main"><div className="top"><div><div className="title">{view==='dashboard'?'Business overview':view==='leads'?'Lead intelligence':view==='copilot'?'AI Copilot':'Recommendations'}</div><div className="muted" style={{fontSize:13,marginTop:5}}>{session.user.email}</div></div></div>{view==='dashboard'?<Overview session={session}/>:view==='leads'?<Leads session={session}/>:view==='copilot'?<Copilot session={session}/>:<Recommendations session={session}/>}</main></div>}
async function api(path:string,session:any,options?:RequestInit){const token=session.access_token;const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options?.headers||{})}});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data}
function useData(session:any){const [data,setData]=useState<any>({leads:[],sales:[],expenses:[]});const [error,setError]=useState('');useEffect(()=>{Promise.all([api('/api/leads',session),api('/api/sales',session),api('/api/expenses',session)]).then(([l,s,e])=>setData({leads:l.leads||[],sales:s.sales||[],expenses:e.expenses||[]})).catch(e=>setError(e.message))},[session]);return {...data,error}}
function Overview({session}:{session:any}){const {leads,sales,expenses,error}=useData(session);const revenue=sales.reduce((a:(n:number),x:Sale)=>a+Number(x.amount),0);const cost=expenses.reduce((a:number,x:Expense)=>a+Number(x.amount),0);return <><div className="grid4"><Metric label="Revenue" value={`$${revenue.toLocaleString()}`} /><Metric label="Expenses" value={`$${cost.toLocaleString()}`} /><Metric label="Active Leads" value={String(leads.filter((x:Lead)=>x.temperature!=='cold').length)} /><Metric label="Pipeline" value={`$${leads.reduce((a:number,x:Lead)=>a+Number(x.value||0),0).toLocaleString()}`} /></div>{error?<div className="card" style={{marginTop:14}}><div className="error">{error}</div><div className="muted">Make sure Supabase has been configured and the database schema has been run.</div></div>:<div className="grid2"><div className="card"><h3>Priority leads</h3>{leads.slice(0,8).map((l:Lead)=><div className="row" key={l.id}><div><span className="score">{l.score}</span> <strong>{l.customers?.name||'Lead'}</strong></div><span className={`pill ${l.temperature}`}>{l.temperature}</span></div>)}{!leads.length&&<div className="muted">No leads yet. Add data to see intelligence here.</div>}</div><div className="card"><h3>What BizPilot does</h3><p className="muted">It reads your sales, expenses, customers and leads, then turns them into practical actions.</p><p className="muted">Start by adding your business data in Supabase or through the CSV importer we will add next.</p></div></div>}</>}
function Metric({label,value}:{label:string;value:string}){return <div className="card"><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div>}
function Leads({session}:{session:any}){const {leads,error}=useData(session);return <div className="card"><h3>Leads ranked by score</h3>{error&&<div className="error">{error}</div>}{leads.map((l:Lead)=><div className="row" key={l.id}><div><span className="score">{l.score}</span><strong>{l.customers?.name||'Lead'}</strong><div className="muted" style={{fontSize:12,marginLeft:42}}>{l.customers?.email||''}</div></div><div><span className={`pill ${l.temperature}`}>{l.temperature}</span> <span className="muted">${Number(l.value||0).toLocaleString()}</span></div></div>)}{!leads.length&&!error&&<p className="muted">No leads found.</p>}</div>}
function Copilot({session}:{session:any}){const [q,setQ]=useState('');const [messages,setMessages]=useState<any[]>([]);const [busy,setBusy]=useState(false);const ask=async(text:string)=>{if(!text.trim())return;setBusy(true);setMessages(m=>[...m,{role:'user',text}]);setQ('');try{const d=await api('/api/ai/copilot',session,{method:'POST',body:JSON.stringify({question:text})});setMessages(m=>[...m,{role:'ai',text:d.answer}])}catch(e:any){setMessages(m=>[...m,{role:'ai',text:e.message}])}finally{setBusy(false)}};return <div className="card chat"><div className="messages">{messages.length===0&&<><p className="muted">Ask about your actual business data.</p>{['Why did my sales change?','Which leads should I contact?','What should I focus on today?'].map(x=><button key={x} className="btn secondary" onClick={()=>ask(x)}>{x}</button>)}</>}{messages.map((m,i)=><div key={i} className={`bubble ${m.role==='user'?'user':''}`}>{m.text}</div>)}{busy&&<div className="bubble loading">Thinking…</div>}</div><div className="chatbar"><input className="input" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask(q)}} placeholder="Ask BizPilot…"/><button className="btn" onClick={()=>ask(q)} disabled={busy}>Ask</button></div></div>}
function Recommendations({session}:{session:any}){const [result,setResult]=useState<any>(null);const [busy,setBusy]=useState(true);const [error,setError]=useState('');useEffect(()=>{api('/api/ai/copilot',session).then(setResult).catch(e=>setError(e.message)).finally(()=>setBusy(false))},[session]);return <div className="card">{busy?<p className="muted">Generating today's business brief…</p>:error?<div className="error">{error}</div>:<><h3>Today's business brief</h3><p style={{whiteSpace:'pre-wrap',lineHeight:1.7}}>{result.synthesis}</p><hr style={{borderColor:'#262b36'}}/><p className="muted"><strong>Financial:</strong> {result.financial}</p><p className="muted"><strong>Sales:</strong> {result.sales}</p><p className="muted"><strong>Customers:</strong> {result.customer}</p></>}</div>}
