import Anthropic from "@anthropic-ai/sdk";
const anthropic=new Anthropic({apiKey:process.env.ANTHROPIC_API_KEY});const MODEL="claude-sonnet-4-6";
interface BusinessSnapshot{revenue:{current:number;previous:number};expenses:{current:number;previous:number};leads:Array<{name:string;score:number;reason:string;value:number}>;customers:Array<{name:string;lifetimeValue:number;inactiveDays:number}>;topProducts:Array<{name:string;revenue:number;growthPct:number}>}
async function callAgent(systemPrompt:string,userPrompt:string){const response=await anthropic.messages.create({model:MODEL,max_tokens:600,system:systemPrompt,messages:[{role:"user",content:userPrompt}]});const block=response.content.find(b=>b.type==="text");return block&&block.type==="text"?block.text:"";}
export async function runFinancialAgent(s:BusinessSnapshot){const c=pctChange(s.revenue.current,s.revenue.previous);return callAgent("You are BizPilot's Financial Intelligence Agent. Analyze revenue and expenses for a small business. Be concise and cite only supplied numbers. Never give tax, legal, or accounting advice.",`Revenue: $${s.revenue.current} (${c}% vs last period). Expenses: $${s.expenses.current} (previous: $${s.expenses.previous}). Summarize in 2-3 sentences.`)}
export async function runSalesAgent(s:BusinessSnapshot){const leads=s.leads.slice(0,5).map(l=>`${l.name} (score ${l.score}, $${l.value}, ${l.reason})`).join("; ");return callAgent("You are BizPilot's Sales Agent. Analyze lead priority using only the supplied data.",`Top leads: ${leads}. Identify the 3 highest-priority actions in 2-3 sentences.`)}
export async function runCustomerIntelligenceAgent(s:BusinessSnapshot){const atRisk=s.customers.filter(c=>c.inactiveDays>30);return callAgent("You are BizPilot's Customer Intelligence Agent. Analyze customer inactivity and reactivation opportunity using only supplied data.",`${atRisk.length} customers inactive 30+ days, combined lifetime value $${atRisk.reduce((x,c)=>x+c.lifetimeValue,0)}. Summarize risk and opportunity in 2-3 sentences.`)}
export async function runRecommendationAgent(s:BusinessSnapshot){const [financial,sales,customer]=await Promise.all([runFinancialAgent(s),runSalesAgent(s),runCustomerIntelligenceAgent(s)]);const synthesis=await callAgent("You are BizPilot's Recommendation Agent. Turn the three findings into 3-5 short prioritized actions. Do not invent numbers.",`Financial Agent: ${financial}\n\nSales Agent: ${sales}\n\nCustomer Intelligence Agent: ${customer}`);return{financial,sales,customer,synthesis};}
export async function answerCopilotQuestion(question:string,s:BusinessSnapshot){return callAgent("You are BizPilot AI, a business copilot. Answer using ONLY the supplied business snapshot. Cite numbers when available. If data does not cover the question, say so plainly.",`Business data snapshot: ${JSON.stringify(s)}\n\nQuestion: ${question}`)}
function pctChange(a:number,b:number){if(b===0)return"0";return(((a-b)/b)*100).toFixed(1)}
